### ISSUE TITLE
OOM when training TPVFormer for 3D semantic occupancy prediction task on A100 with 40G GPU memory

### ISSUE THREAD

**Issue by lhyakn** [wzzheng/TPVFormer#10]
Hi! I want to train the semantic occupancy prediciton task, but after I run the following command: 

`bash launcher.sh config/tpv04_occupancy.py out/tpv_occupancy --lovasz-input voxel`

I got an OOM error, I'm a little confused because in the README you say that you successfully trained with RTX3090, any suggestions?

**Comment by wzzheng** [comment]
Thanks for reporting this, we will look into this asap!

**Comment by huang-yh** [comment]
We tried again, and it successfully run on RTX3090, consuming 23225 MB GPU memory.
We also carried out experiments on A100 before, and it was okay. Here is the detailed information about our conda environment on the A100 machine [https://cloud.tsinghua.edu.cn/f/635d0964f7e44e4f9c32/?dl=1]. Note that some of these packages are not required.

**Comment by lhyakn** [comment]
> We tried again, and it successfully run on RTX3090, consuming 23225 MB GPU memory. We also carried out experiments on A100 before, and it was okay. Here is the detailed information about our conda environment on the A100 machine [https://cloud.tsinghua.edu.cn/f/635d0964f7e44e4f9c32/?dl=1]. Note that some of these packages are not required.

Oh, thanks for your help, I just tested it again and now there is no problem, I don't know what the problem is, but now the program works fine.

**Comment by lhyakn** [comment]
But I have one more question, I read your code carefully and I am a bit confused about the calculation of interval, why is it subtracted by one here?
https://github.com/wzzheng/TPVFormer/blob/27627079bbb87ae1b8e0b3acf9a1a8f4cdc81cfe/dataloader/dataset_wrapper.py#L90

**Comment by wzzheng** [comment]
> > We tried again, and it successfully run on RTX3090, consuming 23225 MB GPU memory. We also carried out experiments on A100 before, and it was okay. Here is the detailed information about our conda environment on the A100 machine [https://cloud.tsinghua.edu.cn/f/635d0964f7e44e4f9c32/?dl=1]. Note that some of these packages are not required.
> 
> Oh, thanks for your help, I just tested it again and now there is no problem, I don't know what the problem is, but now the program works fine.

Thanks for the update!

**Comment by wzzheng** [comment]
> But I have one more question, I read your code carefully and I am a bit confused about the calculation of interval, why is it subtracted by one here?
> 
> https://github.com/wzzheng/TPVFormer/blob/27627079bbb87ae1b8e0b3acf9a1a8f4cdc81cfe/dataloader/dataset_wrapper.py#L90

We follow Cylinder3D for doing this. It seems like a bug and we will fix this. Thanks!

**Comment by lhyakn** [comment]
> > But I have one more question, I read your code carefully and I am a bit confused about the calculation of interval, why is it subtracted by one here?
> > https://github.com/wzzheng/TPVFormer/blob/27627079bbb87ae1b8e0b3acf9a1a8f4cdc81cfe/dataloader/dataset_wrapper.py#L90
> 
> We follow Cylinder3D for doing this. It seems like a bug and we will fix this. Thanks!

Hi, did you guys solve this problem? I tried to remove the minus one part of the code, but I encountered the following problem, the error reporting is very vague and I don't know how to fix it. 

`torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGABRT`


BTW, congratulation on your paper being accepted by CVPR!

**Comment by huang-yh** [comment]
The operation of clipping to the maximum in the following line may generate grid index of 200 or 16 (take grid size of [200, 200, 16] as an example) which may cause the error of "list index out of range". This is the possible reason for your problem we have identified so far.
https://github.com/wzzheng/TPVFormer/blob/71a14392b212f179a3f7835202ea3230869384af/dataloader/dataset_wrapper.py#L94
You can fix it by using "max_bound - 1e-3" as the clipping upper bound.

**Comment by lhyakn** [comment]
> The operation of clipping to the maximum in the following line may generate grid index of 200 or 16 (take grid size of [200, 200, 16] as an example) which may cause the error of "list index out of range". This is the possible reason for your problem we have identified so far.
> 
> https://github.com/wzzheng/TPVFormer/blob/71a14392b212f179a3f7835202ea3230869384af/dataloader/dataset_wrapper.py#L94
> 
> You can fix it by using "max_bound - 1e-3" as the clipping upper bound.

Yes I think the minus one operation is also to avoid this problem, but it looks like your solution is more intuitive, thanks!

**Comment by lhyakn** [comment]
> We tried again, and it successfully run on RTX3090, consuming 23225 MB GPU memory. We also carried out experiments on A100 before, and it was okay. Here is the detailed information about our conda environment on the A100 machine [https://cloud.tsinghua.edu.cn/f/635d0964f7e44e4f9c32/?dl=1]. Note that some of these packages are not required.

Hi! sorry to bother you, I found that although the program successfully run on A100, it consumes 39G GPU memory, it is normal? can you give me some help please?

**Comment by huang-yh** [comment]
We also ran into this problem on A100. The GPU memory consumed on A100 and RTX 3090 varies largely, and we are also working on it. You can try using an even larger model to see if it will actually run out of memory. Or, you can try decreasing the feature dimension from 256 to 128.

**Comment by lhyakn** [comment]
Got it. I think this issue might have to do with PyTorch's memory management system. I'll close this issue for now and hopefully we can make some progress on it.
