### ISSUE TITLE
Request for visualization code.

### ISSUE THREAD

**Issue by cskkxjk** [wzzheng/TPVFormer#12]
Hello! I wonder if you can release the code and colormap about the visualization of output 3D occupancy results. Thank you.

**Comment by yuhsuanyeh** [comment]
I am interested in visualization as well!

**Comment by wzzheng** [comment]
Thanks for your interest! We will organize and release the visualization code before this weekend.

**Comment by wzzheng** [comment]
Hi, the visualization code has been released! Feel free to use them and give us suggestions!
