### ISSUE TITLE
Table lidarseg not found

### ISSUE THREAD

**Issue by drilistbox** [wzzheng/TPVFormer#13]
File "/opt/conda/lib/python3.7/site-packages/nuscenes/nuscenes.py", line 214, in get
    assert table_name in self.table_names, "Table {} not found".format(table_name)
AssertionError: Table lidarseg not found

**Comment by zzk785089755** [comment]
You should download nuscenes-lidarseg and unpack it with nuscenes full datasets.

**Comment by 1561213** [comment]
1、在https://www.nuscenes.org/nuscenes#download下载nuScenes-lidarseg。
2、将外层v1.0-trainval下的category.json等2个文件放入与maps同级的v1.0-trainval下，若提示已存在，替换掉原文件（注意先保存旧文件），不替换会提示“AssertionError: Please use the category.json that comes with nuScenes-lidarseg, and not the old category.json.”
3、将lidarseg文件夹放入与maps、sweeps、samples同级文件下，之后的文件路径为：v1.0-trainval/xxxx.bin.注意这里不要嵌套两层lidarseg，一层即可。

**Comment by minhoooo1** [comment]
> 1、在[https://www.nuscenes.org/nuscenes#download下载nuScenes-lidarseg。](https://www.nuscenes.org/nuscenes#download%E4%B8%8B%E8%BD%BDnuScenes-lidarseg%E3%80%82) 2、将外层v1.0-trainval下的category.json等2个文件放入与maps同级的v1.0-trainval下，若提示已存在，替换掉原文件（注意先保存旧文件），不替换会提示“AssertionError: Please use the category.json that comes with nuScenes-lidarseg, and not the old category.json.” 3、将lidarseg文件夹放入与maps、sweeps、samples同级文件下，之后的文件路径为：v1.0-trainval/xxxx.bin.注意这里不要嵌套两层lidarseg，一层即可。

大哥您好，可以直接提供一个目录结构的截图嘛？ 感谢麻烦您了
