### ISSUE TITLE
train on v1.0-mini ??

### ISSUE THREAD

**Issue by Rex-LK** [wzzheng/TPVFormer#14]
I want train on v1.0-mini dataset, how can I generate thenuscenes_infos_train.pkl/nuscenes_infos_val.pkl of v1.0-mini dataset

**Comment by huang-yh** [comment]
We generate the pkl files for v1.0-mini, and you can now download them at https://cloud.tsinghua.edu.cn/f/2e8201181e3443d1b823/?dl=1 [nuscenes_infos_train_mini.pkl] and https://cloud.tsinghua.edu.cn/f/7e9ada6c2f4b49d89a9f/?dl=1 [nuscenes_infos_val_mini.pkl].

**Comment by Rex-LK** [comment]
> We generate the pkl files for v1.0-mini, and you can now download them at https://cloud.tsinghua.edu.cn/f/2e8201181e3443d1b823/?dl=1 [nuscenes_infos_train_mini.pkl] and https://cloud.tsinghua.edu.cn/f/7e9ada6c2f4b49d89a9f/?dl=1 [nuscenes_infos_val_mini.pkl].

ok，thank you very much
