### ISSUE TITLE
请问论文有直接跟3d occupancy feature效果做对比吗？

### ISSUE THREAD

**Issue by chenzyhust** [wzzheng/TPVFormer#15]
您好作者，论文中比较大的一个优化就是使用3个平面（HW， ZH， ZW）代替3d occupancy feature（HWZ），请问有直接对比过性能和显存速度指标吗？

**Comment by lyfadvance** [comment]
这个确实是一个很重要的点。作者可以做一下对比实验，获取一下数据，造福我们这些没有V100的人。。

**Comment by lyfadvance** [comment]
另外，根据论文的说法
![image](https://user-images.githubusercontent.com/32757235/220073600-88c47b95-e70a-4ab1-93d7-e3a6bd5b1d17.png)
其实还是构造了一个[H W D C]的vox 特征空间。按照这个做法的话，内存和cpu的复杂度，貌似还是HxWxDxC。是我哪里理解不对吗？

**Comment by wzzheng** [comment]
是的，这个是个很重要的对比。我们做了一些初步的实验，如下表所示。不过目前基于voxel的性能还没有调到最优，之后我们也计划开源这些baseline的代码。
![Picture1](https://user-images.githubusercontent.com/44290343/220105388-6e1b9fd9-a3ee-4d84-b67b-4e4c0dc5a5e9.png)

**Comment by wzzheng** [comment]
> 另外，根据论文的说法 ![image](https://user-images.githubusercontent.com/32757235/220073600-88c47b95-e70a-4ab1-93d7-e3a6bd5b1d17.png) 其实还是构造了一个[H W D C]的vox 特征空间。按照这个做法的话，内存和cpu的复杂度，貌似还是HxWxDxC。是我哪里理解不对吗？

这个因为我们只是在最后一步得到voxel的特征空间，而无需在这个voxel上进行很多操作，所以复杂度会比较低。

**Comment by zhangzaibin** [comment]
这篇论文想法真的很好，我私下尝试过直接在voxel上做监督训练，但是很难训练。希望作者以后能开源用voxel训练的pipeline。

**Comment by wzzheng** [comment]
> 这篇论文想法真的很好，我私下尝试过直接在voxel上做监督训练，但是很难训练。希望作者以后能开源用voxel训练的pipeline。

谢谢，基于voxel的代码我们会在这两天开源，敬请期待~

**Comment by chenzyhust** [comment]
@wzzheng 论文还会更新voxel和tpv在显存，速度，性能上的详细对比吗？还有tpv没有实现temporal fusion，这个还会做吗？

**Comment by wzzheng** [comment]
> @wzzheng 论文还会更新voxel和tpv在显存，速度，性能上的详细对比吗？还有tpv没有实现temporal fusion，这个还会做吗？

都会更新的，目前还在测试中。temporal fusion也正在做

**Comment by QingXIA233** [comment]
对于没有A100和3090的情况，如果想在Tesla V100上做tpv的相关训练测试，是否有可能呢？tpv中是否有某些设计可以修改来减小显存占用来让我们能够使用V100呢？

**Comment by huang-yh** [comment]
You can use smaller image backbone, i.e. ResNet50, smaller input image resolution, i.e. 450x800, and smaller TPV feature dimension, i.e. 64, to reduce GPU memory consumption.
We have noticed that the image backbone and the 3D reconstruction from TPV planes are the two parts that account for most of the GPU memory consumption.
