### ISSUE TITLE
TypeError: No matching definition for argument type(s) array(uint8, 3d, C), array(int32, 2d, C).

### ISSUE THREAD

**Issue by wi11Iam5-mpu** [wzzheng/TPVFormer#19]
Thanks for your excellent work.
But, I am unable to successfully run any scripts on v1.0-mini. 
I made sure to look through previous issues, downloaded the corresponding .pkl file and followed the instructions to execute the script. However, I always encounter a problem on line 100 of dataset_wrapper.py (update to line 91):
`processed_label = nb_process_label(np.copy(processed_label), label_voxel_pair)` 
raise `TypeError: No matching definition for argument type(s) array(uint8, 3d, C), array(int32, 2d, C)`.

**Comment by wi11Iam5-mpu** [comment]
I confirm that this issue is related to Numba’s signature, but I don’t know the specific reason.

**Comment by huang-yh** [comment]
Hi, we successfully ran a training script on v1.0-mini just now.
Given your bug report, we suggest replacing the original signature with "uint8\[:,:,:\](uint8\[:,:,:\],int32\[:,:\])" or "uint8\[:,:,:\](uint8\[:,:,:\],int64\[:,:\])".
https://github.com/wzzheng/TPVFormer/blob/207358903342962df1b69cd7da27301241df39dc/dataloader/dataset_wrapper.py#L99

**Comment by wi11Iam5-mpu** [comment]
> Hi, we successfully ran a training script on v1.0-mini just now. Given your bug report, we suggest replacing the original signature with "uint8[:,:,:](uint8[:,:,:],int32[:,:])" or "uint8[:,:,:](uint8[:,:,:],int64[:,:])".
> 
> https://github.com/wzzheng/TPVFormer/blob/207358903342962df1b69cd7da27301241df39dc/dataloader/dataset_wrapper.py#L99

Thx. I made it.
