### ISSUE TITLE
Question about the label

### ISSUE THREAD

**Issue by scuizhibin** [wzzheng/TPVFormer#3]
What is the label of the network? How do you deal with it? Thanks to the author.

**Comment by wzzheng** [comment]
We use the sparse lidar segmentation labels to train the network.
The trained model can generalize them to other areas in the scene.

**Comment by scuizhibin** [comment]
Is&nbsp;&nbsp;the&nbsp;code&nbsp;open&nbsp;source&nbsp;on&nbsp;weekends？


---Original---
From: &quot;Wenzhao ***@***.***&gt;
Date: Wed, Feb 8, 2023 16:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wzzheng/TPVFormer] Question about the label (Issue #3)




 
We use the sparse lidar segmentation labels to train the network.
 The trained model can generalize them to other areas in the scene.
 
&mdash;

**Comment by wzzheng** [comment]
Yes.

**Comment by scuizhibin** [comment]
大佬，代码更新了吗？


---Original---
From: &quot;Wenzhao ***@***.***&gt;
Date: Wed, Feb 8, 2023 16:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wzzheng/TPVFormer] Question about the label (Issue #3)




 
Yes.
 
&mdash;

**Comment by wzzheng** [comment]
更新了！

**Comment by scuizhibin** [comment]
大佬&nbsp;抱大腿


---Original---
From: &quot;Wenzhao ***@***.***&gt;
Date: Sun, Feb 12, 2023 21:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wzzheng/TPVFormer] Question about the label (Issue #3)




 
更新了！
 
&mdash;

**Comment by FrontierBreaker** [comment]
What's the difference between [nuscenes-noIgnore.yaml] and nuscenes.yaml ? Hope for detailed explanation. Thanks!! @wzzheng

**Comment by scuizhibin** [comment]
怎么制作生成训练的标签？是nuscenes自带的吗？


---Original---
From: ***@***.***&gt;
Date: Tue, Feb 14, 2023 18:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wzzheng/TPVFormer] Question about the label (Issue #3)




 
What's the difference between [nuscenes-noIgnore.yaml] and nuscenes.yaml ? Hope for detailed explanation. Thanks!! @wzzheng
 
&mdash;

**Comment by wzzheng** [comment]
> 怎么制作生成训练的标签？是nuscenes自带的吗？
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, Feb 14, 2023 18:07 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [wzzheng/TPVFormer] Question about the label (Issue #3) What's the difference between [nuscenes-noIgnore.yaml] and nuscenes.yaml ? Hope for detailed explanation. Thanks!! @wzzheng &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

是的，Panoptic nuScenes有这个标签

**Comment by huang-yh** [comment]
> What's the difference between [nuscenes-noIgnore.yaml] and nuscenes.yaml ? Hope for detailed explanation. Thanks!! @wzzheng

The nuscenes-noIgnore.yaml assigns voxels without any annotation an "empty" label, and is used for 3D semantic occupancy prediction. The nuscenes.yaml does not have the "empty" class and simply ignores voxels without annotation when calculating losses, and thus is used for the lidar segmentation task.

**Comment by FrontierBreaker** [comment]
got it, thanks!

**Comment by anhquancao** [comment]
> We use the sparse lidar segmentation labels to train the network. The trained model can generalize them to other areas in the scene.

Hi, congratulations on your awesome work! Out of curiosity, have you ever experimented with accumulating lidar scans to generate denser labels for training purposes?

**Comment by wzzheng** [comment]
> > We use the sparse lidar segmentation labels to train the network. The trained model can generalize them to other areas in the scene.
> 
> Hi, congratulations on your awesome work! Out of curiosity, have you ever experimented with accumulating lidar scans to generate denser labels for training purposes?

Yes. Actually, we plan to release a paper doing this recently. Stay tuned!

**Comment by anhquancao** [comment]
Thank you for the information!
