### ISSUE TITLE
Question about train/val pickle files.

### ISSUE THREAD

**Issue by lhyakn** [wzzheng/TPVFormer#6]
Thanks for your great work! I have a question about train/val pickle files, is there any difference between the pickle file you provided and the pickle file generated by mmdet3d? Can I use the mmdet3d pickle files instead?

**Comment by huang-yh** [comment]
The pickle file we use is the same with Cylinder3D, and I am not sure whether it differs from the file generated by mmdet3d. It is recommended to use the files we provide, or modify the following function if the files from mmdet3d are preferred. https://github.com/wzzheng/TPVFormer/blob/16a517d730b296a3ecb07ee6af50134b0522d684/dataloader/dataset.py#L50

**Comment by lhyakn** [comment]
Got it! thanks!
